### ISSUE TITLE
Errors when running script

### ISSUE THREAD

**Issue by kryokil** [m2sup3rn0va/RASEv1#1] opened 2020-12-20 20:39 UTC
Hi, thank you for making this guide. I have spent countless hours trying to get api30 working with root but no luck. I have followed your guide. All is working up to the point when I run script. Could you please check whether I did something wrong or there is an error somewhere. This is error log from powershell.

```
At D:\downloads\root\RASEv1-main\Build-RootAVD.ps1:349 char:96
+ ... avd $avd -writable-system -selinux permissive -no-snapshot-load &).Id
+                                                                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\downloads\root\RASEv1-main\Build-RootAVD.ps1:531 char:106
+ ... vd -writable-system -selinux permissive -snapshot $avd"_Rooted" &).Id
+                                                                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\downloads\root\RASEv1-main\Build-RootAVD.ps1:537 char:130
+ ... inux permissive -snapshot $avd"_Rooted" -http-proxy $http_proxy &).Id
+                                                                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\downloads\root\RASEv1-main\Build-RootAVD.ps1:722 char:102
+ ... vd -writable-system -selinux permissive -snapshot $avd"_Rooted" &).Id
+                                                                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

Many thanks again for your time and effort. 

All the best

**Comment by m2sup3rn0va** [comment] 2020-12-21 15:30
Hey kryokil

Thanks for pointing that out.
The issue is not actually with the script.

You are getting this error because you are using Powershell window and it doesn't understand '&' without quotes.
I created and tested this script on "Windows Terminal" and there are no issues but Powershell window, for some weird reason doesn't understand '&' without quotes. So to solve this you have two ways :

Easy one and a good  one : Install Windows Terminal for Store (It's Free 👍 ) and then  you can use the script and it works like a charm
Manual and Boring : Find all the lines where you have & mentioned and replace that with "&" and you are good to go.

Also, I have updated the README and the script. So, please download the latest script and do let me know what you think.

**Comment by kryokil** [comment] 2020-12-21 15:47
Lovely, will update after I test your suggestion.

**Comment by kryokil** [comment] 2020-12-21 20:29
Ok, after some edits and bit of fighting :D i come to hold on this.

```
[+] NOTE : MAKE SURE THAT NONE OF THE EMULATORS ARE RUNNING

[+] Hit Enter to Confirm:

[+] Starting AVD : 'pixel5'
invalid command-line parameter: &.
Hint: use '@foo' to launch a virtual device named 'foo'.
please use -help for more information
[+] AVD Started with Job ID :

[+] Extract Emulator Name via ADB
* daemon not running; starting now at tcp:5037
* daemon started successfully
initialize-rootavd : You cannot call a method on a null-valued expression.
At line:1 char:1
+ initialize-rootavd
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Initialize-RootAVD], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Initialize-RootAVD

PS D:\avd>
```
Now im stuck. Would you have any suggestion on this please? Thank you as usual ;)

**Comment by m2sup3rn0va** [comment] 2020-12-21 20:39
Are you using PowerShell window again, if yes, please stop using it and try it with **'Windows Terminal'** and let me know

**Comment by kryokil** [comment] 2020-12-21 22:01
I am using Windows Terminal. Installed yesterday but still was getting few errors regarding & symbol.

I managed to get to this point. ALso one weird thing when I run windows terminal it still say Windows Powershell but its different from powershell. I really dont know what im doing wrong. Sorry

```
[+] Starting AVD : 'pixel5'
handleCpuAcceleration: feature check for hvf
added library vulkan-1.dll
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
```

[]https://image.prntscr.com/image/QO9uFGt9R_epCUvo1VKldg.png

**Comment by m2sup3rn0va** [comment] 2020-12-22 14:17
In Windows Terminal, if you open POWERSHELL, there are certain things which behaves differently (not sure why).
But these errors should not come if you have followed the instructions step by step.

You can try `adb kill-server` and `adb start-server`.
I hope this will work but to understand this better, please share the complete logs on the console and also do let me know the screenshot of the image used for the emulator.

Also check if you have `adb.exe` and `emulator.exe` in the `%PATH%`

**Comment by m2sup3rn0va** [comment] 2020-12-22 17:36
So before I start my apologies, I completely forgot that I was using POWERSHELL v7.1 and not 5.0 which is by default installed on windows.

Please download POWERSHELL from github (latest one) or version above 7.1 and run the `pwsh.exe` file which comes with it to run the script.

Let me know if this works for you.

Also, try `adb.exe kill-server` and `adb.exe start-server` to restart `adb`

**Comment by m2sup3rn0va** [comment] 2020-12-29 09:13
The issue is resolved because the script is being updated.
Now it supports default powershell version i.e 5.1 as well which is shipped with windows.

This is also tested on windows powershell version 5.1 and version 7.1
Hence, closing the ticket.

**Closed as completed by m2sup3rn0va** 2020-12-29 09:13 UTC
